apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-database-postgres
  labels:
    app: app-database-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-database-postgres
  template:
    metadata:
      labels:
        app: app-database-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: shorturl
            - name: POSTGRES_PASSWORD
              value: changeme
          image: postgres
          imagePullPolicy: IfNotPresent
          name: app-database-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
          ports:
            - containerPort: 5432
      volumes:
        - emptyDir: {}
          name: postgresql-data
