#!/bin/bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-docker-k8s
  labels:
    app: react-docker-k8s
spec:
  replicas: 0
  selector:
    matchLabels:
      app: react-docker-k8s
  template:
    metadata:
      labels:
        app: react-docker-k8s
    spec:
      containers:
        - name: react-docker-k8s
          image: sourabhopn/demo:react-app
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
