apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          env:
            - name: PORT
              value: "8989"
            - name: DB_HOST
              value: "3.144.6.137"
            - name: FE_APP
              value: http://3.144.6.137:30902
            - name: DB_PORT
              value: "30866"
          image: ghcr.io/sourabhraghavopn/go-app:master
          ports:
            - containerPort: 8989
